version: '2'
services:
  mysql:
    image: mysql
    command: --init-file /data/application/init.sql --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
        - ./init.sql:/data/application/init.sql
    environment:
      MYSQL_ROOT_PASSWORD: UseADifferentPassword
  springboot-mysql-docker:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - mysql
